#!/bin/bash 

###### 12/14/2011 ###################
# SETUP ENS CQPF PROCESSING VARIABLES
#####################################

####################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
####################################################

export RUN_ENVIR=${RUN_ENVIR:-nco}
set -xa

module load grib_util

#export IOBUF_PARAMS='*:sync,%stdout:sync'

####################################
# Specify NET and RUN Name and model
####################################

export NET=${NET:-gens}
export RUN=${RUN:-gefs}

#########################################
# Run config file to get input parameters
#########################################

if [ "$RUN_ENVIR" = dev ]      ### For Developers
then
  PARA_CONFIG=${PARA_CONFIG:-${NWROOT}/${direxp}/parm/gefs_arch_pgrb2ap5_config}
  . $PARA_CONFIG
fi

##########################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
##########################################################

if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export DBNROOT=/nwprod/spa_util/fakedbn
  export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
fi

export PS4='$SECONDS + '
date

########################################################
# obtain unique process id (pid) and make temp directory
########################################################

export pid=$$
export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=$DATAROOT/${job}.${pid}

mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

##################
# File To Log Msgs
##################

export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

#####################################
# Determine Job Output Name on System
#####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
#export pgmout="OUTPUT.${pid}"
export pgmout="OUTPUT"

##############################################
# SENDECF  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##############################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

###################################################################
# RUNJOB   - Judge the Job for Regular Run or Extended 00 Cycle Run
###################################################################
export RUNJOB=${RUNJOB:-REGULAR}
 
#########################
# Specify Execution Areas
#########################

export HOMEgefs=${HOMEgefs:-$NWROOT/naefs.${naefs_ver}}
export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
export USHgefs=${USHgefs:-$HOMEgefs/ush}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. PDY

########################
# Define COM directories
########################

export COMIN=/lfs/h1/ops/prod/com/gefs/v12.3
export COMOUT=/lfs/h2/emc/vpppg/noscrub/$LOGNAME/ncep_gefs_0.5d

export COMINccpa=${COMINccpa:-${COMROOT}/ccpa/prod}
mkdir -m 775 -p $COMOUT

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

####################
# Execute the script
####################
$HOMEgefs/scripts/exgefs_arch_prcp_pgrb2ap5.sh.ecf

#############################################################

cat $pgmout.*
msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
rm -rf $DATA

date
