#!/bin/sh

#set -x

echo " +++++++++++++++++++++++++++++++++++++++++++++++++"
echo " +++++++++ GDIT CACTUS !!!!!!!!!!! +++++++++++++++"
echo " +++++++++ GDIT CACTUS !!!!!!!!!!! +++++++++++++++"
echo " +++++++++ GDIT CACTUS !!!!!!!!!!! +++++++++++++++"
echo " +++++++++ GDIT CACTUS !!!!!!!!!!! +++++++++++++++"
echo " +++++++++++++++++++++++++++++++++++++++++++++++++"

###
### define the directory and utility
###

export nhours=/apps/ops/prod/nco/core/prod_util.v2.0.5/exec/ndate
export windex=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/grbindex
export WGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib
export COPYGB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/copygb
export SHOME=/lfs/h2/emc/vpppg/save
export GLOBAL=/lfs/h2/emc/ens/noscrub/emc.ens/common/data
export ptmp=/lfs/h2/emc/ptmp
export GTMP=$ptmp
export PTMP=$ptmp
export NGLOBAL=/lfs/h2/emc/vpppg/noscrub
export SSUB=/u/$LOGNAME/save/xbin/sub_wcoss2

cd $SHOME/run_web;pwd

###
### get real time from IBM-SP computer system
###

Date=`date +%y%m%d`
CDATE=20$Date\00
echo "CDATE=$CDATE"

###
### Define the time for each cycle and different days
###

export CDATEp06=`$nhours +06 $CDATE`
export CDATEm06=`$nhours -06 $CDATE`
export CDATEm12=`$nhours -12 $CDATE`
export CDATEm18=`$nhours -18 $CDATE`
export CDATEm24=`$nhours -24 $CDATE`
export CDATEm30=`$nhours -30 $CDATE`
export CDATEm36=`$nhours -36 $CDATE`
export CDATEm42=`$nhours -42 $CDATE`
export CDATEm48=`$nhours -48 $CDATE`
export CDATEm54=`$nhours -54 $CDATE`
export CDATEm60=`$nhours -60 $CDATE`
export CDATEm72=`$nhours -72 $CDATE`
export CDATEm84=`$nhours -84 $CDATE`
export CDATEm96=`$nhours -96 $CDATE`
export CDATEm108=`$nhours -108 $CDATE`
export CDATEm120=`$nhours -120 $CDATE`
export CDATEm360=`$nhours -360 $CDATE`
export CDATEp00=$CDATE
export CDATEp12=`$nhours +12 $CDATE`
export CDATEp24=`$nhours +24 $CDATE`
export YMDM1=`$nhours -24 $CDATE | cut -c1-8`
export YMDM2=`$nhours -48 $CDATE | cut -c1-8`
export YMDM3=`$nhours -72 $CDATE | cut -c1-8`
export YMDM4=`$nhours -96 $CDATE | cut -c1-8`
export YMDM5=`$nhours -120 $CDATE | cut -c1-8`
export YMDM6=`$nhours -144 $CDATE | cut -c1-8`
export YMDM7=`$nhours -168 $CDATE | cut -c1-8`
export YMDM8=`$nhours -192 $CDATE | cut -c1-8`
export YMDM9=`$nhours -216 $CDATE | cut -c1-8`
export YMDM10=`$nhours -240 $CDATE | cut -c1-8`
export YMDM15=`$nhours -360 $CDATE | cut -c1-8`
export YMDM16=`$nhours -384 $CDATE | cut -c1-8`
export YMDM17=`$nhours -408 $CDATE | cut -c1-8`
export CYMD=`echo $CDATE | cut -c1-8`
export CYMDM1=`echo $CDATEm24 | cut -c1-8`
export YYYYMM=`$nhours -120 $CDATE | cut -c1-6`
export YYYY=`echo $CDATE | cut -c1-4`
export MMDD=`echo $CDATE | cut -c5-8`
export DD=`echo $CDATE | cut -c7-8`
export HH=`echo $CDATE | cut -c9-10`

$SHOME/$LOGNAME/ccpa/tskr_prec/3hr_CCPA/jobs/JCCPA_CONUS.sms.prod.archiveonly_cactus $YMDM15 $YMDM1
#$SHOME/$LOGNAME/cqpf/plot_cqpf/scripts/run_ccpa.sh $CDATEm360 $CDATEp00
#$SHOME/$LOGNAME/run_web/clean_files_on_rzdm.sh > /u/$LOGNAME/save/arch/clean_files_on_rzdm.log
exit

# NEXT JOB TIME is 7:00am EST for summer time   
# NEXT JOB TIME is 6:00am EST for winter time

ISUMTIM=36
IWINTIM=35
ADDHR=$IWINTIM
NEXT_JOB_TIME=`$nhours +$ADDHR $CDATE`
CUE=dev_transfer


echo "++++++ Submit process 1 deg model precipitation forecast data Job              ++++++"

export CDATE=$YMDM1\00
out=$GTMP/$LOGNAME/output/get_gefs_apcp.out; rm $out
job=/u/$LOGNAME/save/updated_cqpf_new/jobs/get_gefs_apcp.sh
$SSUB -a GEFS-DEV -q $CUE -p 1/1/S -r 1024/1 -w +0000 -t 6:00:00 -j GET_GEFS_APCP -o $out $job


echo "++++++ Submit extract 0.5 deg model precipitation forecast data Job              ++++++"

out=$GTMP/$LOGNAME/output/save_gefs_data.out; rm $out
job=/u/$LOGNAME/save/naefs.v6.0.1/mycron/save_gefs_data.sh 
$SSUB -a GEFS-DEV -q $CUE -p 1/1/S -r 512/1 -w +0100 -t 6:00:00 -j SAVE_GEFS_APCP -o $out $job
#$SSUB -a GEFS-DEV -q $CUE -p 1/1/S -r 512/1 -w +0000 -t 6:00:00 -j SAVE_GEFS_APCP -o $out $job

###
### Submit the schedual job itself   
###

echo "++++++ Submite the GARCH job ++++++"
out=/u/$LOGNAME/save/arch/GARCHcactus.out; tail -1000 $out > $GTMP/$LOGNAME/tmpfile; mv $GTMP/$LOGNAME/tmpfile $out
job=/lfs/h2/emc/vpppg/save/bo.cui/run_web/GARCH_cactus
$SSUB -a GEFS-DEV -q $CUE -p 1/1/S -r 1024/1 -w ${NEXT_JOB_TIME} -t 6:00:00 -j GARCH_cactus -o $out $job

eval primary=`cat  /lfs/h1/ops/prod/config/prodmachinefile | grep primary`
eval backup=`cat  /lfs/h1/ops/prod/config/prodmachinefile | grep backup`

echo $primary "and " $backup

isdogwood=primary:dogwood

if [  $primary != $isdogwood ]; then
   echo  " Check plotting jobs on dogwood!"
else
echo " cactus is the production machine! "
echo " Send web plots through cactus "


echo "++++++ Submite the ENSPOST_00 job ++++++"
### contains 6-hourly precipitation types map job ###
### contains 24-hour CMRF/MRF CPQPF/PQPF comparing forecast maps  ###
###    all 24hr maps are inside of $HOME/wpqpf/scripts/www_200312.qsub
### adding CMC's test 24-hr QPF and PQPF maps to this jib -08/17/2004
export CDATE=$CDATEp00
out=$GTMP/$LOGNAME/output/ens00.out; rm -f $out
job=$SHOME/$LOGNAME/garch/earch_00/scripts/ENSPOST_00.sh
$SSUB -a NAEFS-DEV -q $CUE -p 1/1/S -r 512/1 -w +0000 -t 6:00:00 -j ens00 -o $out $job

###
### Submit daily esemble verification job and probability job
###  plot RMOP ( Relative measurement of predictability ) maps
###

echo "++++++ Submite the EPROB_f job ++++++"
export CDATE=$CDATEp00
out=$GTMP/$LOGNAME/output/eprob_f.out; rm -f $out
job=$SHOME/$LOGNAME/garch/eprob/scripts/dailyopr_eprob_f.llq
$SSUB -a GEFS-DEV -q $CUE -p 1/1/S -r 512/1 -w +0120 -t 6:00:00 -j eprob_f -o $out $job

echo "++++++ Submite the EPROB_a job ++++++"
export CDATE=$CDATEp00
out=$GTMP/$LOGNAME/output/eprob_a.out; rm -f $out
job=$SHOME/$LOGNAME/eprob/scripts/dailyopr_eprob_a.llq
#sub_wcoss2 -a GEFS-DEV -q $CUE -p 1/1/S -r 512/1 -w +0130 -t 6:00:00 -j eprob_a -o $out $job
$SSUB -a GEFS-DEV -q $CUE -p 1/1/S -r 512/1 -w +0130 -t 6:00:00 -j eprob_a -o $out $job

fi #if [  $prod == dogwood ]; then

$SHOME/ccpa/tskr_prec/3hr_CCPA/jobs/JCCPA_CONUS.sms.prod.archiveonly_cactus $YMDM15 $YMDM1
$SHOME/cqpf/plot_cqpf/scripts/run_ccpa.sh $CDATEm360 $CDATEp00
$SHOME/run_web/clean_files_on_rzdm.sh > /u/$LOGNAME/save/arch/clean_files_on_rzdm.log


