SHELL= 	/bin/bash
INC=     ${G2_INC4}
LIBS=    ${G2_LIB4} ${W3NCO_LIB4} ${BACIO_LIB4} ${JASPER_LIB} ${PNG_LIB} ${Z_LIB}
SRCSf90= gefs_pgrb_enspqpf.f90 printinfr.f90 init_parm.f90
SRCS=    $(SRCSf90) 
OBJS=    $(SRCSf:.f=.o) $(SRCSf90:.f90=.o)
CMD=   	gefs_pgrb_enspqpf
FC= 	ifort
FFLAGS = -O3 -g -convert big_endian -I $(INC)
LDFLAGS=

# Lines from here on down should not need to be changed.  They are the
# actual rules which make uses to build a.out.
#
all:    $(CMD)

$(CMD):		$(OBJS)
	$(FC) $(LDFLAGS) -o $(@) $(OBJS) $(LIBS)
	rm -f $(OBJS)

$(OBJS):        $(SRCS)
	$(FC) $(FFLAGS) -c $(SRCS)

$(OBJS):        makefile

allclean:       clean all

clean:
	-rm -f $(OBJS)

clobber:        clean
	-rm -f $(CMD)

install:
	mv $(CMD) ../../exec/$(CMD)


